apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "multinic-agent.fullname" . }}-crd
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "multinic-agent.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-25"
data:
  multinicnodeconfig-crd.yaml: |
{{ .Files.Get "crds/multinicnodeconfig-crd.yaml" | indent 4 }}