{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "multinic-agent.fullname" . }}
  labels:
    {{- include "multinic-agent.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "watch", "delete"]
- apiGroups: ["multinic.io"]
  resources: ["multinicnodeconfigs"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "update", "patch", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "multinic-agent.fullname" . }}-status
  labels:
    {{- include "multinic-agent.labels" . | nindent 4 }}
rules:
- apiGroups: ["multinic.io"]
  resources: ["multinicnodeconfigs/status"]
  verbs: ["update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "multinic-agent.fullname" . }}
  labels:
    {{- include "multinic-agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "multinic-agent.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "multinic-agent.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "multinic-agent.fullname" . }}-status
  labels:
    {{- include "multinic-agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "multinic-agent.fullname" . }}-status
subjects:
- kind: ServiceAccount
  name: {{ include "multinic-agent.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
