{{- $db := .Values.database | default dict -}}
{{- if ($db.enabled | default false) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "multinic-agent.fullname" . }}-db
  labels:
    {{- include "multinic-agent.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ ($db.password | default "") | b64enc | quote }}
{{- end }}
