apiVersion: multinic.io/v1alpha1
kind: MultiNicNodeConfig
metadata:
  name: viola2-biz-master01
  namespace: multinic-system
  labels:
    multinic.io/node-name: viola2-biz-master01
    multinic.io/instance-id: 84183610-f911-4d8f-9ec2-f35bfeac671f
spec:
  nodeName: viola2-biz-master01
  instanceId: 84183610-f911-4d8f-9ec2-f35bfeac671f
  interfaces:
    - id: 1
      name: multinic0
      macAddress: "fa:16:3e:fb:9b:68"
      address: "11.11.11.132"
      cidr: "11.11.11.0/24"
      mtu: 1450
#    - id: 2
#      macAddress: "fa:16:3e:31:9a:cd"
#      address: "11.11.11.92"
#      cidr: "11.11.11.0/24"
#      mtu: 1450
#    - id: 3
#      macAddress: "fa:16:3e:d8:0f:bb"
#      address: "11.11.11.136"
#      cidr: "11.11.11.0/24"
#      mtu: 1450
