apiVersion: multinic.io/v1alpha1
kind: MultiNicNodeConfig
metadata:
  name: viola2-biz-worker02
  namespace: multinic-system
  labels:
    multinic.io/node-name: viola2-biz-worker02
    multinic.io/instance-id: ba35d476-f810-45a8-b386-270712be6db3
spec:
  nodeName: viola2-biz-worker02
  instanceId: ba35d476-f810-45a8-b386-270712be6db3
  interfaces:
    - id: 1
      macAddress: "fa:16:3e:b6:af:3e"
      address: "11.11.11.63"
      cidr: "11.11.11.0/24"
      mtu: 1450
#    - id: 2
#      macAddress: "fa:16:3e:b0:d5:7c"
#      address: "11.11.11.180"
#      cidr: "11.11.11.0/24"
#      mtu: 1450
#    - id: 3
#      macAddress: "fa:16:3e:c8:11:31"
#      address: "11.11.11.7"
#      cidr: "11.11.11.0/24"
#      mtu: 1450
