apiVersion: multinic.io/v1alpha1
kind: MultiNicNodeConfig
metadata:
  name: viola2-biz-worker03
  namespace: multinic-system
  labels:
    multinic.io/node-name: viola2-biz-worker03
spec:
  nodeName: viola2-biz-worker03
  interfaces:
    - id: 1
      macAddress: "fa:16:3e:c9:e4:ba"
      address: "11.11.11.39"
      cidr: "11.11.11.0/24"
      mtu: 1500
