apiVersion: multinic.io/v1alpha1
kind: MultiNicNodeConfig
metadata:
  name: master2
  namespace: multinic-system
  labels:
    multinic.io/node-name: master2
spec:
  nodeName: master2
  interfaces:
    - id: 1
      macAddress: "fa:16:3e:d5:07:35"
      address: "11.11.11.34"
      cidr: "11.11.11.0/24"
      mtu: 1500

