apiVersion: multinic.io/v1alpha1
kind: MultiNicNodeConfig
metadata:
  name: master1
  namespace: multinic-system
  labels:
    multinic.io/node-name: master1
spec:
  nodeName: master1
  interfaces:
    - id: 1
      macAddress: "fa:16:3e:f3:b0:3f"
      address: "11.11.11.33"
      cidr: "11.11.11.0/24"
      mtu: 1500

