apiVersion: multinic.io/v1alpha1
kind: MultiNicNodeConfig
metadata:
  name: viola2-biz-master03
  namespace: multinic-system
  labels:
    multinic.io/node-name: viola2-biz-master03
    multinic.io/instance-id: 9c5667a1-6df1-4b27-9c4c-0db430a745ed
spec:
  nodeName: viola2-biz-master03
  instanceId: 9c5667a1-6df1-4b27-9c4c-0db430a745ed
  interfaces:
    - id: 1
      macAddress: "fa:16:3e:d5:4f:88"
      address: "11.11.11.29"
      cidr: "11.11.11.0/24"
      mtu: 1500
    - id: 2
      macAddress: "fa:16:3e:5c:a2:69"
      address: "11.11.11.35"
      cidr: "11.11.11.0/24"
      mtu: 1500
