apiVersion: multinic.io/v1alpha1
kind: MultiNicNodeConfig
metadata:
  name: viola2-biz-master03
  namespace: multinic-system
  labels:
    multinic.io/node-name: viola2-biz-master03
    multinic.io/instance-id: 9c5667a1-6df1-4b27-9c4c-0db430a745ed
spec:
  nodeName: viola2-biz-master03
  instanceId: 9c5667a1-6df1-4b27-9c4c-0db430a745ed
  interfaces:
    - id: 1
      name: multinic0
      macAddress: "fa:16:3e:ba:51:f7"
      address: "11.11.11.159"
      cidr: "11.11.11.0/24"
      mtu: 1450
#    - id: 2
#      macAddress: "fa:16:3e:42:c3:ae"
#      address: "11.11.11.126"
#      cidr: "11.11.11.0/24"
#      mtu: 1450
#    - id: 3
#      macAddress: "fa:16:3e:dc:81:42"
#      address: "11.11.11.101"
#      cidr: "11.11.11.0/24"
#      mtu: 1450
