apiVersion: multinic.io/v1alpha1
kind: MultiNicNodeConfig
metadata:
  name: viola2-biz-master02
  namespace: multinic-system
  labels:
    multinic.io/node-name: viola2-biz-master02
    multinic.io/instance-id: 57a9a0d6-315c-412b-a12a-975574d2b690
spec:
  nodeName: viola2-biz-master02
  instanceId: 57a9a0d6-315c-412b-a12a-975574d2b690
  interfaces:
    - id: 0
      name: multinic0
      macAddress: "fa:16:3e:16:d6:24"
      address: "11.11.11.130"
      cidr: "11.11.11.0/24"
      mtu: 1450
#    - id: 2
#      macAddress: "fa:16:3e:11:a2:96"
#      address: "11.11.11.86"
#      cidr: "11.11.11.0/24"
#      mtu: 1450
#    - id: 3
#      macAddress: "fa:16:3e:1f:ba:20"
#      address: "11.11.11.41"
#      cidr: "11.11.11.0/24"
#      mtu: 1450
