apiVersion: multinic.io/v1alpha1
kind: MultiNicNodeConfig
metadata:
  name: viola2-biz-worker03
  namespace: multinic-system
  labels:
    multinic.io/node-name: viola2-biz-worker03
    multinic.io/instance-id: d4defd76-faa9-4ae1-a228-13f90505f3d3
spec:
  nodeName: viola2-biz-worker03
  instanceId: d4defd76-faa9-4ae1-a228-13f90505f3d3
  interfaces:
    - id: 1
      macAddress: "fa:16:3e:30:32:87"
      address: "11.11.11.245"
      cidr: "11.11.11.0/24"
      mtu: 1450
#    - id: 2
#      macAddress: "fa:16:3e:c9:2e:85"
#      address: "11.11.11.55"
#      cidr: "11.11.11.0/24"
#      mtu: 1450
#    - id: 3
#      macAddress: "fa:16:3e:47:d0:a0"
#      address: "11.11.11.228"
#      cidr: "11.11.11.0/24"
#      mtu: 1450
